highlighter: rouge
permalink: ./:title
title: "Weak Notes"
description: "// A working in public, second brain"
owner:
  name: thechelsuk
  email: "feedback@thechels.uk"
  uri: https://thechels.uk
  avatar: "/.well-known/avatar.png"
url: https://thechels.uk
encoding: UTF-8
future: false
github:
  repository_url: https://github.com/thechelsuk/uk.thechels
  branch: main
sass:
  style: compressed
webmentions:
  username: thechels.uk
  cache_folder: .cache
  cache_bad_uris_for: 5
  js: false
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: monthly
    older: monthly
  syndication:
    mastodon:
      endpoint: https://brid.gy/publish/mastodon
    bluesky:
      endpoint: https://brid.gy/publish/bluesky
    reddit:
      endpoint: https://brid.gy/publish/reddit
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      syndicate_to: [mastodon, bluesky, reddit]
plugins:
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-webmention_io
collections:
  rss:
    output: false
  ways:
    output: true
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - ".well-known"
  - "_pages"
  - "_ways"
  - "assets"

# Site Navigation
## Header
navigation_header:
  - link: "/about"
    title: "About"
  - link: "/slashes"
    title: "Pages"
  - link: "https://links.thechels.uk"
    title: "Links &neArr;"
  - link: "https://tools.thechels.uk"
    title: "Tools &neArr;"
  - link: "https://shop.thechels.uk"
    title: "Shop &neArr;"

## SubMenu
navigation_data:
  - link: "/daily"
    title: "Daily Briefing"
  - link: "/feeds"
    title: "Feeds"
  - link: "/books"
    title: "Books"
  - link: "/tag/mixtapes"
    title: "Mixtapes"
  - link: "/teams"
    title: "Live Teams"
  - link: "/jokes"
    title: "Jokes"
  - link: "/podcasts"
    title: "Podcasts"
  - link: "/blogroll"
    title: "Blogroll"
  - link: "/slogans"
    title: "Slogans"
  - link: "/films"
    title: "Films"
  - link: "/constraints"
    title: "Constraints"
  - link: "/videos"
    title: "Videos"
  - link: "/sitemap"
    title: "Sitemap (xml)"

## SubMenu
navigation_slashes:
  - link: "/ai"
    title: "AI"
  - link: "/apps"
    title: "Apps"
  - link: "/about"
    title: "About"
  - link: "/accessibility"
    title: "Accessibility"
  - link: "/architecture"
    title: "Architecture"
  - link: "/.well-known/avatar.png"
    title: "Avatar (png)"
  - link: "/cv"
    title: "CV"
  - link: "/disability"
    title: "Disability"
  - link: "/drafts"
    title: "Draft Actions"
  - link: "/green"
    title: "Green"
  - link: "/manual"
    title: "Manual"
  - link: "/now"
    title: "Now"
  - link: "/pgp"
    title: "PGP key"
  - link: "/.well-known/privacy.txt"
    title: "Privacy (txt)"
  - link: "/projects"
    title: "Projects"
  - link: "/nnw-themes"
    title: "NetNewsWire Themes"
  - link: "/save"
    title: "Save"
  - link: "/SBOM"
    title: "Software Bill of Materials (SBOM)"
  - link: "/.well-known/security.txt"
    title: "Security (txt)"
  - link: "/style"
    title: "Style Guide"
  - link: "/uses"
    title: "Uses"
  - link: "/verify"
    title: "Verify"
  - link: "/ways/"
    title: "Ways"
  - link: "/indieweb.txt"
    title: "IndieWeb (txt)"

## Footer links
navigation_footer:
  - link: "/feed"
    title: "Feed (xml)"
  - link: "/feed.json"
    title: "Feed (json)"
  - link: "/rss.xml"
    title: "Feed - Alt (xml)"
  - link: "/robots.txt"
    title: "Robots (txt)"
  - link: "/llms.txt"
    title: "LLMs (txt)"
  - link: "/sitemap.xml"
    title: "Sitemap (xml)"
  - link: "/save"
    titlr: "Sponsors" 
    
  - link: "/accessibility"
    title: "Accessibility"
  - link: "/humans.txt"
    title: "Humans (txt)"
  - link: "/humans.json"
    title: "Humans (json)"
  - link: "/.well-known/privacy.txt"
    title: "Privacy (txt)"
  - link: "/.well-known/security.txt"
    title: "Security (txt)"
  - link: "/.well-known/change-password"
    title: "Change password"
  - link: "/.well-known/dnt-policy.txt"
    title: "DNT Policy (txt)"

  - link: "/about#colophon"
    title: "Colophon"
  - link: "https://shop.thechels.uk"
    title: "Shop &neArr;"
  - link: "https://tools.thechels.uk"
    title: "Tools &neArr;"
  - link: "https://bsky.app/profile/thechels.uk"
    title: "Bluesky &neArr;"
  - link: "https://mastodon.social/@Thechelsuk"
    title: "Mastodon &neArr;"
