---
name: Add Film
on:
    repository_dispatch:
    workflow_dispatch:
        inputs:
            imdb_id:
                description: "IMDb ID"
                required: true
            rating:
                description: "rating"
                required: true

concurrency:
    group: add-film
    cancel-in-progress: false

env:
    actor: ${{ github.actor }}
    owner: ${{ github.repository_owner }}
    github_token: ${{ secrets.GITHUB_TOKEN }}
    omdb_key: ${{ secrets.OMDB_API_KEY }}

jobs:
    Build:
        name: Builder
        if: ${{ github.actor == github.repository_owner }}
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.PAT_TOKEN }}

            - name: Pull latest changes
              run: |
                  git pull origin main
            - name: Set up Python and dependencies
              uses: ./.github/actions/python-setup
              with:
                  python-version: "3.13"
            - name: Run add_film script
              run: |
                  python '_python/add_film.py' --imdb_id "${{ inputs.imdb_id }}" --rating "${{ inputs.rating }}"
            - name: Commit and push
              uses: ./.github/actions/git-commit-back
              with:
                  message: "Chore: Add film ${{ inputs.imdb_id }} [skip ci]"
