---
name: Add Book
on:
    workflow_dispatch:
        inputs:
            isbn:
                description: "ISBN"
                required: true
env:
    actor: ${{ github.actor }}
    owner: ${{ github.repository_owner }}
    github_token: ${{ secrets.GITHUB_TOKEN }}
jobs:
    Build:
        runs-on: ubuntu-latest
        if: ${{ github.actor == github.repository_owner }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.PAT_TOKEN }}

            - name: Set up Python and dependencies
              uses: ./.github/actions/python-setup
              with:
                  python-version: "3.13"

            - name: Run add_book script
              run: |
                  python '_python/add_book.py' --isbn "${{ inputs.isbn }}"

            - name: Commit and push
              uses: ./.github/actions/git-commit-back
              with:
                  message: "Chore: Add book ${{ inputs.isbn }} [skip ci]"
