name: Fetch social posts

on:
    schedule:
        - cron: "0 */2 * * *"
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    fetch-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Install Python Dependencies
              run: python -m pip install -r "requirements.txt" --quiet

            - name: Fetch social posts
              run: |
                  python _python/fetch/fetch_social_posts.py
                  python _python/fetch/fetch_videos.py
                  python _python/fetch/fetch_releases.py

            - name: Commit updated YAML (if changed)
              run: |
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git add -A
                  git diff --staged --quiet || git commit -m "chore: update PESOS files"
                  git push
