---
name: Reusable Runner

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            label:
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

jobs:
    Build:
        runs-on: ubuntu-latest
        name: Processing
        steps:
            - name: Check out repo
              uses: actions/checkout@v7

            - name: Set up Python and dependencies
              uses: ./.github/actions/python-setup
              with:
                  python-version: 3.13.1

            - name: Check for new content
              env:
                  CONTENT: ${{ inputs.content }}
                  LABEL: ${{ inputs.label }}
              run: |-
                  python '_python/yaml_updater.py' --content "$CONTENT" --label "$LABEL"
            - name: set title
              id: title
              env:
                  ISSUE_TITLE: ${{ github.event.issue.title }}
              run: |-
                  echo "title=Feat: $ISSUE_TITLE" >> $GITHUB_OUTPUT
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8
              env:
                  ISSUE_BODY: ${{ github.event.issue.body }}
                  ISSUE_TITLE: ${{ github.event.issue.title }}
                  ISSUE_NUMBER: ${{ github.event.issue.number }}
              with:
                  committer: GitHub Action <action@github.com>
                  branch: "new-config-from-issue-${{ github.event.issue.number }}"
                  delete-branch: true
                  title: "Feat: ${{ github.event.issue.title}}"
                  body: |
                      > ${{ github.event.issue.body }}
                      Automatic PR for Config change: ${{ steps.title.outputs.title }}
                      Closes #${{ github.event.issue.number }}
                  reviewers: "${{ github.repository_owner }}"
                  commit-message: "feat-${{ steps.title.outputs.title }}-#${{ github.event.issue.number }}"
