---
name: Reusable Runner

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            label:
                required: true
                type: string

jobs:
    Build:
        runs-on: ubuntu-latest
        name: Processing
        steps:
            - name: Check out repo
              uses: actions/checkout@v6

            - name: Set up Python and dependencies
              uses: ./.github/actions/python-setup
              with:
                  python-version: 3.13.1

            - name: Check for new content
              run: |-
                  python '_python/yaml_updater.py' --content "${{ inputs.content }}" --label "${{ inputs.label }}"
            - name: set title
              id: title
              run: |-
                  echo "title=Feat: ${{ github.event.issue.title}}" >> $GITHUB_OUTPUT
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8
              with:
                  committer: GitHub Action <action@github.com>
                  branch: "new-config-from-issue-${{ github.event.issue.number }}"
                  delete-branch: true
                  title: "Feat: ${{ github.event.issue.title}}"
                  body: |
                      > ${{ github.event.issue.body }}
                      Automatic PR for Config change: ${{ steps.title.outputs.title }}
                      Closes #${{ github.event.issue.number }}
                  reviewers: "${{ github.repository_owner }}"
                  commit-message: "feat-${{ steps.title.outputs.title }}-#${{ github.event.issue.number }}"
