---
name: x - Link Checker

on:
    workflow_dispatch:
    schedule:
        - cron: "0 20 1 * *"

permissions:
    issues: write

jobs:
    linkChecker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: ".ruby-version"
                  bundler-cache: true

            - name: Build site
              run: bundle exec jekyll build --trace

            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v2.8.0
              with:
                  args: >-
                      --verbose
                      --no-progress
                      --include-fragments
                      --offline
                      --base-url "$PWD/_site"
                      --root-dir "$PWD/_site"
                      --remap 'https?://thechels\.uk(/.*)? file://$PWD/_site$1'
                      --exclude '^https?://'
                      --timeout=30
                      --max-retries=2
                      './_site/**/*.html'
                  fail: false
                  format: markdown
                  jobSummary: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Issue From File
              if: steps.lychee.outputs.exit_code != 0
              uses: peter-evans/create-issue-from-file@v6
              with:
                  title: Link Checker Report - ${{ github.run_id }}
                  content-filepath: ./lychee/out.md
                  labels: |
                      Bot
